[package]
org = "wso2"
name = "greeter"
version = "0.1.0"
distribution = "2201.1.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"